# hlsl2msl.cmake
# Converts an HLSL shader to MSL via SPIR-V and wraps it as a C++ source file.
#
# Called as a cmake script: cmake -DSHADER=<hlsl> -DCLASS=<name> -DSTAGE=<vert|frag|comp>
#                                 -DINCLUDE_DIRS=<dirs> -DOUTPUT=<msl.cpp>
#                                 -DGLSLANG=<path> -DSPIRV_CROSS=<path>
#                                 -P hlsl2msl.cmake

# Map stage name to glslangValidator stage flag
if(STAGE STREQUAL "vert")
    set(GLSL_STAGE "vert")
elseif(STAGE STREQUAL "frag")
    set(GLSL_STAGE "frag")
elseif(STAGE STREQUAL "comp")
    set(GLSL_STAGE "comp")
else()
    message(STATUS "[hlsl2msl] Skipping unsupported stage: ${STAGE} for ${CLASS}")
    # Write an empty source so the build doesn't fail
    file(WRITE "${OUTPUT}" "// ${CLASS}: stage '${STAGE}' not supported for MSL conversion\n")
    return()
endif()

# Build include dir args as a proper list for execute_process
set(INCLUDE_ARGS "")
if(INCLUDE_DIR1)
    list(APPEND INCLUDE_ARGS "-I${INCLUDE_DIR1}")
endif()
if(INCLUDE_DIR2)
    list(APPEND INCLUDE_ARGS "-I${INCLUDE_DIR2}")
endif()

set(SPIRV_FILE "${OUTPUT}.spv")

# Read the HLSL source to find entry point names
file(READ "${SHADER}" _shader_src)

# Find all entry point candidates: functions with SV_ semantics or [numthreads]
# For compute: look for [numthreads(...)] followed by void funcname(
# For vertex: look for funcname(...) returning struct with SV_Position
# For fragment: look for funcname(...) : SV_Target
# Simplest: extract all function names that look like entry points
set(_entry_points "")
if(STAGE STREQUAL "comp")
    string(REGEX MATCHALL "void[ \t]+([a-zA-Z_][a-zA-Z0-9_]*)[ \t]*\\(" _matches "${_shader_src}")
    foreach(_m ${_matches})
        string(REGEX MATCH "void[ \t]+([a-zA-Z_][a-zA-Z0-9_]*)" _dummy "${_m}")
        list(APPEND _entry_points "${CMAKE_MATCH_1}")
    endforeach()
elseif(STAGE STREQUAL "frag")
    # Fragment entry points return something : SV_Target
    string(REGEX MATCHALL "[a-zA-Z0-9_]+[ \t]+([a-zA-Z_][a-zA-Z0-9_]*)[ \t]*\\([^)]*\\)[ \t]*:[ \t]*SV_Target" _matches "${_shader_src}")
    foreach(_m ${_matches})
        string(REGEX MATCH "[ \t]+([a-zA-Z_][a-zA-Z0-9_]*)[ \t]*\\(" _dummy "${_m}")
        list(APPEND _entry_points "${CMAKE_MATCH_1}")
    endforeach()
else()
    # Vertex: try main, then any function returning a struct
    set(_entry_points "main")
endif()

# Always try "main" first
list(INSERT _entry_points 0 "main")
list(REMOVE_DUPLICATES _entry_points)

# Try each entry point until one succeeds
set(_all_msl "")
set(_any_success FALSE)

foreach(_entry ${_entry_points})
    set(_spv "${SPIRV_FILE}.${_entry}")
    # Shift SSBO bindings by 9 to avoid overlap with UBO bindings (b0-b11)
    # while keeping everything under Metal's 31-slot limit
    set(_cmd ${GLSLANG} -D -e ${_entry} -S ${GLSL_STAGE} -V
        --shift-ssbo-binding ${GLSL_STAGE} 9)
    if(INCLUDE_DIR1)
        list(APPEND _cmd -I${INCLUDE_DIR1})
    endif()
    if(INCLUDE_DIR2)
        list(APPEND _cmd -I${INCLUDE_DIR2})
    endif()
    list(APPEND _cmd -o ${_spv} ${SHADER})
    execute_process(
        COMMAND ${_cmd}
        RESULT_VARIABLE GLSLANG_RESULT
        ERROR_VARIABLE GLSLANG_ERROR
        OUTPUT_QUIET
    )
    if(NOT GLSLANG_RESULT EQUAL 0)
        continue()
    endif()

    execute_process(
        COMMAND ${SPIRV_CROSS} ${_spv} --msl --msl-version 20100 --msl-decoration-binding
        RESULT_VARIABLE CROSS_RESULT
        ERROR_VARIABLE CROSS_ERROR
        OUTPUT_VARIABLE _msl_chunk
    )
    file(REMOVE ${_spv})

    if(CROSS_RESULT EQUAL 0)
        set(_any_success TRUE)
        if(_all_msl STREQUAL "")
            set(_all_msl "${_msl_chunk}")
        endif()
        # For now, use only the first successful entry point to avoid duplicate definitions
        break()
    endif()
endforeach()

if(NOT _any_success)
    message(WARNING "[hlsl2msl] No entry points compiled for ${CLASS}")
    file(WRITE "${OUTPUT}" "// ${CLASS}: all entry points failed — HLSL source kept as fallback\n")
    set(_orig_cpp "${OUTPUT}")
    string(REPLACE "_msl.cpp" ".cpp" _orig_cpp "${_orig_cpp}")
    if(EXISTS "${_orig_cpp}")
        file(READ "${_orig_cpp}" _orig_content)
        string(REPLACE "#ifndef __APPLE__\n" "" _orig_content "${_orig_content}")
        string(REPLACE "\n#endif // !__APPLE__\n" "" _orig_content "${_orig_content}")
        file(WRITE "${_orig_cpp}" "${_orig_content}")
    endif()
    return()
endif()

set(MSL_SOURCE "${_all_msl}")

# Step 3: no post-processing needed — we don't use --msl-decoration-binding

# Wrap MSL source as C++ raw string literal
# No escaping needed — R"MSLSRC(...)MSLSRC" handles everything
file(WRITE "${OUTPUT}"
"// Generated by hlsl2msl.cmake — DO NOT EDIT
#ifdef __APPLE__
#include \"${CLASS}.h\"

const std::string ${CLASS}::_source = std::string(R\"MSLSRC(
${MSL_SOURCE})MSLSRC\");
#endif // __APPLE__
")
