name: CMake

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset windows-release

    - name: Build
      run: cmake --build --preset windows-release-all
